[versions]
slf4j = "2.0.17"
guice = "7.0.0"
postgresql = "42.7.5"
logback = "1.5.18"
junit = "5.10.0"
checkstyle = "10.23.1"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
google-guice = { module = "com.google.inject:guice", version.ref = "guice" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
puppycrawl-checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
